### ISSUE TITLE
Incompatible with Sodium

### ISSUE THREAD

**Issue by squiig** [Snownee/SnowRealMagic#420]
### Mod loader

NeoForge

### Minecraft version

1.21.1

### Mod version

11.0.13-neoforge

### Modloader version

NeoForge 21.1.95

### Modpack info

https://www.feed-the-beast.com/modpacks/125-ftb-evolution

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

(My latest.log is too big for Pastebin. Please tell me which parts you would like to see.)

I hope this can be fixed, because I really love mods like this but it is so buggy right now that I'm forced to turn it off...

Example A: **_Vanilla (!!)_** short grass, ferns, and stone walls are completely invisible because of the snow. This is in an Alpine Highlands biome (I think from Oh The Biomes We've Gone).

![Image](https://github.com/user-attachments/assets/682ed9b1-aee0-44af-b481-98a68bdddaf2)

Example B: This is the roof of an Apotheosis tower after a snowstorm.

![Image](https://github.com/user-attachments/assets/d0a8e8d8-6834-4d5f-b9c4-f205bc61ab87)

![Image](https://github.com/user-attachments/assets/c4a5e1f1-1fc6-48a5-83fb-da53adb398ea)

Example C: Glitched rock piles and ice chunks from Project Vibrant Journeys, presumably because snow is trying to merge with it.

![Image](https://github.com/user-attachments/assets/07d59304-43f9-40f6-8f46-8b43dcaf54a4)

**Comment by Meshiest** [comment]
Was able to fix this on my end by switching from Sodium to Embeddium, and adding Monocle for Iris for shaders

**Comment by KostromDan** [comment]
> Was able to fix this on my end by switching from Sodium to Embeddium, and adding Monocle for Iris for shaders

https://github.com/CaffeineMC/sodium/issues/2848

**Comment by KostromDan** [comment]
Embeddium also rederers a little wired.

https://github.com/user-attachments/assets/e313e2a3-2bba-48f9-8a6e-5930e80acdd9

**Comment by Snownee** [comment]
> Embeddium also rederers a little wired.
> 
>  bandicam.2025-03-09.16-50-20-301.mp4

that's unrelated: #278

**Comment by IMS212** [comment]
Should be fixed with https://github.com/CaffeineMC/sodium/commit/c062f1108895bf55aa4b8f89ff7b8a9817e95938

**Comment by Snownee** [comment]
> Should be fixed with [CaffeineMC/sodium@c062f11](https://github.com/CaffeineMC/sodium/commit/c062f1108895bf55aa4b8f89ff7b8a9817e95938)

Thank you

**Comment by mpustovoi** [comment]
I'm still having this issue on NeoForge 1.21.1-21.1.141



Sodium mc1.21.1-0.6.9-neoforge
Snow! Real Magic! 12.0.2+neoforge
Kiwi 15.5.0+neoforge

I guess Sodium has not yet released a version with a fix.

**Comment by KostromDan** [comment]
> I'm still having this issue on NeoForge 1.21.1-21.1.141
> 
> 
> 
> Sodium mc1.21.1-0.6.9-neoforge
> Snow! Real Magic! 12.0.2+neoforge
> Kiwi 15.5.0+neoforge
> 
> I guess Sodium has not yet released a version with a fix.

Sodium fixed it in dev but haven't uploaded release with fix yet.
